/**
 * Tahap 6B — Spesifikasi 32 instrumen (ADDITIVE, DATA ONLY).
 *
 * - Modul paralel BARU; TIDAK menyentuh `instrumentConfig.ts`,
 *   `otbInstrumentConfig.ts`, `brokerSymbols.ts`, maupun `swapCost.ts`.
 *   Seluruh 354 locked tests tetap hijau byte-identik.
 * - Sumber angka: CSV ekspor terminal MT5 (lihat prompt Tahap 6B):
 *   OTB 16 simbol (suffiks _ORB) + Finex 16 simbol (tanpa suffiks,
 *   termasuk US100). Commission per broker dari ekspor terminal 03 Okt 2026
 *   (kolom Commission CSV, dikonfirmasi panel Specification):
 *   OTB (_ORB) = 33.00 USD/lot flat, Finex = 1.00 USD/lot flat.
 *   (Tahap 6D memakai 0.00; dikoreksi Tahap 6G ke angka broker.)
 * - Catatan JPY: target 16-simbol hanya memuat 5 JPY pair per broker
 *   (AUDJPY, CADJPY, CHFJPY, NZDJPY, USDJPY). EURJPY/GBPJPY disebut di
 *   prompt tetapi TIDAK ada di data CSV 16-simbol, sehingga TIDAK
 *   diada-adakan di sini (tanpa angka fiktif). Tahap 6I menutup celah
 *   ini dari bulk export 06 Okt 2026 (EURJPY/GBPJPY masuk terverifikasi).
 * - Tahap 6I (06 Okt 2026): +52 OTB +66 Finex dari bulk export
 *   (SymbolSpecs_OTB_1791247136.csv 68 baris,
 *   SymbolSpecs_Finex_1791247268.csv 82 baris). Tick_Value/komisi/swap
 *   verbatim CSV; GBXUSD dicatat pence (GBX).
 * - Swap_3Day: 3 (Rabu) untuk semua FX; 5 (Jumat) untuk US100.
 * - `leverage: 100000` adalah contract size per CSV (bukan rasio);
 *   nama field dipertahankan sesuai kontrak prompt 6B.
 */

export type SpecBroker = "orbitraderberjangka" | "finex";

export type SpecStatus = "VERIFIED" | "PENDING";

export interface InstrumentSpec {
  symbol: string;
  broker: SpecBroker;
  /** Pip/tick size: 0.00001 (5 digits), 0.001 (3 digits), 0.01 (2 digits). */
  pip: number;
  tickSize: number;
  /** USD per pip per lot (dari CSV; JPY = 0.63). */
  tickValue: number;
  /** Contract size dari CSV (100000 untuk FX). */
  leverage: number;
  /** USD per lot dari kolom Commission CSV (OTB 33.00, Finex 1.00). */
  commission: number;
  /** Swap pips/hari Sen-Kam (dari CSV, bisa negatif/positif/nol). */
  swapLong: number;
  swapShort: number;
  /** Pengali triple-swap (3 untuk JPY pairs; undefined = pakai 3 bila triple day). */
  swapWedMultiplier?: number;
  /** Hari triple-swap MT5 (0-6; 3=Rabu, 5=Jumat untuk US100). */
  swap3DayWeekday?: number;
  baseCurrency: string;
  quoteCurrency: string;
  isJPYPair: boolean;
  status: SpecStatus;
}

function freezeSpec(spec: InstrumentSpec): InstrumentSpec {
  return Object.freeze(spec);
}

function fx(
  symbol: string,
  broker: SpecBroker,
  pip: number,
  tickValue: number,
  swapLong: number,
  swapShort: number,
  baseCurrency: string,
  quoteCurrency: string,
  opts: { swap3DayWeekday?: number } = {},
): InstrumentSpec {
  const isJPYPair = quoteCurrency === "JPY";
  return freezeSpec({
    symbol,
    broker,
    pip,
    tickSize: pip,
    tickValue,
    leverage: 100000,
    // Tahap 6G: komisi per broker dari CSV (OTB 33.00, Finex 1.00).
    commission: broker === "orbitraderberjangka" ? 33.0 : 1.0,
    swapLong,
    swapShort,
    ...(isJPYPair ? { swapWedMultiplier: 3 } : {}),
    swap3DayWeekday: opts.swap3DayWeekday ?? 3,
    baseCurrency,
    quoteCurrency,
    isJPYPair,
    status: "VERIFIED",
  });
}

/**
 * 32 spesifikasi terverifikasi Tahap 6B.
 * Kunci = nama simbol persis (case-sensitive; _ORB signifikan untuk OTB).
 */
export const INSTRUMENT_SPECS_32: Record<string, InstrumentSpec> =
  Object.freeze({
    // ===== OTB VERIFIED (68) — broker orbitraderberjangka =====
    AUDCAD_ORB: fx(
      "AUDCAD_ORB",
      "orbitraderberjangka",
      0.00001,
      0.7,
      -0.75,
      -2.25,
      "AUD",
      "CAD",
    ),
    AUDCHF_ORB: fx(
      "AUDCHF_ORB",
      "orbitraderberjangka",
      0.00001,
      1.21,
      -1.5,
      -1.5,
      "AUD",
      "CHF",
    ),
    AUDJPY_ORB: fx(
      "AUDJPY_ORB",
      "orbitraderberjangka",
      0.001,
      0.63,
      -1.25,
      -1.75,
      "AUD",
      "JPY",
    ),
    AUDNZD_ORB: fx(
      "AUDNZD_ORB",
      "orbitraderberjangka",
      0.00001,
      0.56,
      -1.25,
      -1.75,
      "AUD",
      "NZD",
    ),
    AUDUSD_ORB: fx(
      "AUDUSD_ORB",
      "orbitraderberjangka",
      0.00001,
      1.0,
      -1.5,
      -1.5,
      "AUD",
      "USD",
    ),
    CADJPY_ORB: fx(
      "CADJPY_ORB",
      "orbitraderberjangka",
      0.001,
      0.63,
      -1.25,
      -1.75,
      "CAD",
      "JPY",
    ),
    CHFJPY_ORB: fx(
      "CHFJPY_ORB",
      "orbitraderberjangka",
      0.001,
      0.63,
      -1.75,
      -1.25,
      "CHF",
      "JPY",
    ),
    EURAUD_ORB: fx(
      "EURAUD_ORB",
      "orbitraderberjangka",
      0.00001,
      0.7,
      -1.5,
      -1.5,
      "EUR",
      "AUD",
    ),
    EURCAD_ORB: fx(
      "EURCAD_ORB",
      "orbitraderberjangka",
      0.00001,
      0.7,
      -1.25,
      -1.75,
      "EUR",
      "CAD",
    ),
    EURCHF_ORB: fx(
      "EURCHF_ORB",
      "orbitraderberjangka",
      0.00001,
      1.21,
      -1.75,
      -1.25,
      "EUR",
      "CHF",
    ),
    GBPAUD_ORB: fx(
      "GBPAUD_ORB",
      "orbitraderberjangka",
      0.00001,
      0.7,
      -0.75,
      -2.25,
      "GBP",
      "AUD",
    ),
    GBPUSD_ORB: fx(
      "GBPUSD_ORB",
      "orbitraderberjangka",
      0.00001,
      1.0,
      -2.25,
      -0.75,
      "GBP",
      "USD",
    ),
    NZDJPY_ORB: fx(
      "NZDJPY_ORB",
      "orbitraderberjangka",
      0.001,
      0.63,
      -1.5,
      -1.5,
      "NZD",
      "JPY",
    ),
    USDCAD_ORB: fx(
      "USDCAD_ORB",
      "orbitraderberjangka",
      0.00001,
      0.7,
      -1.5,
      -1.5,
      "USD",
      "CAD",
    ),
    USDCHF_ORB: fx(
      "USDCHF_ORB",
      "orbitraderberjangka",
      0.00001,
      1.21,
      -1.5,
      -1.5,
      "USD",
      "CHF",
    ),
    USDJPY_ORB: fx(
      "USDJPY_ORB",
      "orbitraderberjangka",
      0.001,
      0.63,
      -1.0,
      -2.0,
      "USD",
      "JPY",
    ),

    // ===== FINEX VERIFIED (82) — broker finex =====
    AUDCAD: fx("AUDCAD", "finex", 0.00001, 1.0, -2.39, -2.35, "AUD", "CAD"),
    AUDCHF: fx("AUDCHF", "finex", 0.00001, 1.21, 0.78, -5.25, "AUD", "CHF"),
    AUDJPY: fx("AUDJPY", "finex", 0.001, 0.63, 0.75, -3.95, "AUD", "JPY"),
    AUDNZD: fx("AUDNZD", "finex", 0.00001, 1.0, 0.0, -2.21, "AUD", "NZD"),
    AUDUSD: fx("AUDUSD", "finex", 0.00001, 1.0, -0.96, -3.15, "AUD", "USD"),
    CADJPY: fx("CADJPY", "finex", 0.001, 0.63, -6.32, 0.96, "CAD", "JPY"),
    CHFJPY: fx("CHFJPY", "finex", 0.001, 0.63, -1.98, -1.64, "CHF", "JPY"),
    EURAUD: fx("EURAUD", "finex", 0.00001, 0.7, -6.73, 1.21, "EUR", "AUD"),
    EURCAD: fx("EURCAD", "finex", 0.00001, 1.0, -1.81, -1.67, "EUR", "CAD"),
    EURCHF: fx("EURCHF", "finex", 0.00001, 1.21, 0.69, -4.24, "EUR", "CHF"),
    EURUSD: fx("EURUSD", "finex", 0.00001, 1.0, -4.69, 1.93, "EUR", "USD"),
    GBPUSD: fx("GBPUSD", "finex", 0.00001, 1.0, -1.11, -2.88, "GBP", "USD"),
    NZDJPY: fx("NZDJPY", "finex", 0.001, 0.63, 0.97, -4.73, "NZD", "JPY"),
    USDCHF: fx("USDCHF", "finex", 0.00001, 1.21, 1.01, -7.84, "USD", "CHF"),
    USDJPY: fx("USDJPY", "finex", 0.001, 0.63, 1.95, -7.91, "USD", "JPY"),
   // ===== Tahap 6I (06 Okt 2026): OTB baru dari bulk export
    // SymbolSpecs_OTB_1791247136.csv (Tick_Value/komisi/swap verbatim).
    EURGBP_ORB: freezeSpec({
      symbol: "EURGBP_ORB",
      broker: "orbitraderberjangka",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1.32,
      leverage: 100000,
      commission: 33,
      swapLong: -1.75,
      swapShort: -1.25,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "GBP",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    EURJPY_ORB: freezeSpec({
      symbol: "EURJPY_ORB",
      broker: "orbitraderberjangka",
      pip: 0.001,
      tickSize: 0.001,
      tickValue: 0.63,
      leverage: 100000,
      commission: 33,
      swapLong: -1.75,
      swapShort: -1.25,
      swapWedMultiplier: 3,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "JPY",
      isJPYPair: true,
      status: "VERIFIED",
    }),
    EURNZD_ORB: freezeSpec({
      symbol: "EURNZD_ORB",
      broker: "orbitraderberjangka",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.56,
      leverage: 100000,
      commission: 33,
      swapLong: -1.5,
      swapShort: -1.5,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "NZD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    EURUSD_ORB: freezeSpec({
      symbol: "EURUSD_ORB",
      broker: "orbitraderberjangka",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1,
      leverage: 100000,
      commission: 33,
      swapLong: -2,
      swapShort: -1,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    GBPCAD_ORB: freezeSpec({
      symbol: "GBPCAD_ORB",
      broker: "orbitraderberjangka",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.7,
      leverage: 100000,
      commission: 33,
      swapLong: -1.75,
      swapShort: -1.25,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "CAD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    GBPJPY_ORB: freezeSpec({
      symbol: "GBPJPY_ORB",
      broker: "orbitraderberjangka",
      pip: 0.001,
      tickSize: 0.001,
      tickValue: 0.63,
      leverage: 100000,
      commission: 33,
      swapLong: -1.75,
      swapShort: -1.25,
      swapWedMultiplier: 3,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "JPY",
      isJPYPair: true,
      status: "VERIFIED",
    }),
    GBPNZD_ORB: freezeSpec({
      symbol: "GBPNZD_ORB",
      broker: "orbitraderberjangka",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.56,
      leverage: 100000,
      commission: 33,
      swapLong: -1.25,
      swapShort: -1.75,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "NZD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    NZDUSD_ORB: freezeSpec({
      symbol: "NZDUSD_ORB",
      broker: "orbitraderberjangka",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1,
      leverage: 100000,
      commission: 33,
      swapLong: -1.75,
      swapShort: -1.25,
      swap3DayWeekday: 3,
      baseCurrency: "NZD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    XAGUSD_ORB: freezeSpec({
      symbol: "XAGUSD_ORB",
      broker: "orbitraderberjangka",
      pip: 0.001,
      tickSize: 0.001,
      tickValue: 5,
      leverage: 5000,
      commission: 33,
      swapLong: -1.5,
      swapShort: -1.5,
      swap3DayWeekday: 3,
      baseCurrency: "XAG",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    XAUUSD_ORB: freezeSpec({
      symbol: "XAUUSD_ORB",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -2,
      swapShort: -1,
      swap3DayWeekday: 3,
      baseCurrency: "XAU",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    CLU: freezeSpec({
      symbol: "CLU",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 10,
      leverage: 1000,
      commission: 33,
      swapLong: 0,
      swapShort: 0,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "US100.DEC": freezeSpec({
      symbol: "US100.DEC",
      broker: "orbitraderberjangka",
      pip: 0.25,
      tickSize: 0.25,
      tickValue: 5,
      leverage: 20,
      commission: 33,
      swapLong: 0,
      swapShort: 0,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "US30.DEC": freezeSpec({
      symbol: "US30.DEC",
      broker: "orbitraderberjangka",
      pip: 1,
      tickSize: 1,
      tickValue: 5,
      leverage: 5,
      commission: 33,
      swapLong: 0,
      swapShort: 0,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "US500.DEC": freezeSpec({
      symbol: "US500.DEC",
      broker: "orbitraderberjangka",
      pip: 0.25,
      tickSize: 0.25,
      tickValue: 12.5,
      leverage: 50,
      commission: 33,
      swapLong: 0,
      swapShort: 0,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "AAPL.US": freezeSpec({
      symbol: "AAPL.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "AIG.US": freezeSpec({
      symbol: "AIG.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "AMAZON.US": freezeSpec({
      symbol: "AMAZON.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 1,
      commission: 33,
      swapLong: -10,
      swapShort: -10,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "AMZN.US": freezeSpec({
      symbol: "AMZN.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "APPLE.US": freezeSpec({
      symbol: "APPLE.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 1,
      commission: 33,
      swapLong: -10,
      swapShort: -10,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "AXP.US": freezeSpec({
      symbol: "AXP.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "BA.US": freezeSpec({
      symbol: "BA.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "BABA.US": freezeSpec({
      symbol: "BABA.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "BAC.US": freezeSpec({
      symbol: "BAC.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "BOA.US": freezeSpec({
      symbol: "BOA.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 1,
      commission: 33,
      swapLong: -10,
      swapShort: -10,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "CITI.US": freezeSpec({
      symbol: "CITI.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "CSCO.US": freezeSpec({
      symbol: "CSCO.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "CVX.US": freezeSpec({
      symbol: "CVX.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "DISNEY.US": freezeSpec({
      symbol: "DISNEY.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "EBAY.US": freezeSpec({
      symbol: "EBAY.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "FB.US": freezeSpec({
      symbol: "FB.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 10,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "GE.US": freezeSpec({
      symbol: "GE.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "GOOG.US": freezeSpec({
      symbol: "GOOG.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "GS.US": freezeSpec({
      symbol: "GS.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "HPQ.US": freezeSpec({
      symbol: "HPQ.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "IBM.US": freezeSpec({
      symbol: "IBM.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "INTC.US": freezeSpec({
      symbol: "INTC.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "JNJ.US": freezeSpec({
      symbol: "JNJ.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "JPM.US": freezeSpec({
      symbol: "JPM.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "KO.US": freezeSpec({
      symbol: "KO.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "MA.US": freezeSpec({
      symbol: "MA.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "MCD.US": freezeSpec({
      symbol: "MCD.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "META.US": freezeSpec({
      symbol: "META.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 1,
      commission: 33,
      swapLong: -10,
      swapShort: -10,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "MSFT.US": freezeSpec({
      symbol: "MSFT.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "NVDA.US": freezeSpec({
      symbol: "NVDA.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "ORCL.US": freezeSpec({
      symbol: "ORCL.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "PFE.US": freezeSpec({
      symbol: "PFE.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 10,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "PG.US": freezeSpec({
      symbol: "PG.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "SBUX.US": freezeSpec({
      symbol: "SBUX.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "T.US": freezeSpec({
      symbol: "T.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "V.US": freezeSpec({
      symbol: "V.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "WMT.US": freezeSpec({
      symbol: "WMT.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "XOM.US": freezeSpec({
      symbol: "XOM.US",
      broker: "orbitraderberjangka",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 1,
      leverage: 100,
      commission: 33,
      swapLong: -3.2,
      swapShort: -2.8,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),

    US100: freezeSpec({
      symbol: "US100",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.2,
      // Perbaikan 9 Okt 2026: contract size 20 ($20/poin/lot), bukan 100000.
      // Bukti 2 trade nyata Finex demo: SELL 0.01 @30748.33→30734.16 =
      // +$2.83 (14,17 poin × 0,2); 5,40 poin = +$1.08. tickValue 0.2 ÷
      // tickSize 0.01 = 20. Dulu P&L monitor membengkak 5.000×.
      leverage: 20,
      commission: 1.0,
      swapLong: -25.29,
      swapShort: -117.17,
      swapWedMultiplier: 3,
      swap3DayWeekday: 5, // Jumat (MT5 triple day US100)
      baseCurrency: "US100",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    // ===== Tahap 6I (06 Okt 2026): Finex baru dari bulk export
    // SymbolSpecs_Finex_1791247268.csv.
    "#168": freezeSpec({
      symbol: "#168",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.15,
      swapShort: -7.09,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#388": freezeSpec({
      symbol: "#388",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.15,
      swapShort: -7.09,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#700": freezeSpec({
      symbol: "#700",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.15,
      swapShort: -7.09,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#763": freezeSpec({
      symbol: "#763",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.15,
      swapShort: -7.09,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#AA": freezeSpec({
      symbol: "#AA",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#AAPL": freezeSpec({
      symbol: "#AAPL",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#ADBE": freezeSpec({
      symbol: "#ADBE",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#ADS": freezeSpec({
      symbol: "#ADS",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -5.57,
      swapShort: -6.57,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "EUR",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#AIG": freezeSpec({
      symbol: "#AIG",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#ALV": freezeSpec({
      symbol: "#ALV",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -5.57,
      swapShort: -6.57,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "EUR",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#AMGN": freezeSpec({
      symbol: "#AMGN",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#AXP": freezeSpec({
      symbol: "#AXP",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#BA": freezeSpec({
      symbol: "#BA",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#BIDU": freezeSpec({
      symbol: "#BIDU",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#BLK": freezeSpec({
      symbol: "#BLK",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#BMW": freezeSpec({
      symbol: "#BMW",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -5.57,
      swapShort: -6.57,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "EUR",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#BP": freezeSpec({
      symbol: "#BP",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.99,
      swapShort: -7.99,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "GBP",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#CAT": freezeSpec({
      symbol: "#CAT",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#CME": freezeSpec({
      symbol: "#CME",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#GE": freezeSpec({
      symbol: "#GE",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#GOOGL": freezeSpec({
      symbol: "#GOOGL",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#GS": freezeSpec({
      symbol: "#GS",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#GSK": freezeSpec({
      symbol: "#GSK",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.99,
      swapShort: -7.99,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "GBP",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#HD": freezeSpec({
      symbol: "#HD",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#HSBA": freezeSpec({
      symbol: "#HSBA",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.99,
      swapShort: -7.99,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "GBP",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#IBM": freezeSpec({
      symbol: "#IBM",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#JNJ": freezeSpec({
      symbol: "#JNJ",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#JPM": freezeSpec({
      symbol: "#JPM",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#MA": freezeSpec({
      symbol: "#MA",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#MAR": freezeSpec({
      symbol: "#MAR",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#MCD": freezeSpec({
      symbol: "#MCD",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#META": freezeSpec({
      symbol: "#META",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#MMM": freezeSpec({
      symbol: "#MMM",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#MSFT": freezeSpec({
      symbol: "#MSFT",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#NKE": freezeSpec({
      symbol: "#NKE",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#NVDA": freezeSpec({
      symbol: "#NVDA",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#ORCL": freezeSpec({
      symbol: "#ORCL",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#RL": freezeSpec({
      symbol: "#RL",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.85,
      swapShort: -7.85,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#SAP": freezeSpec({
      symbol: "#SAP",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -5.57,
      swapShort: -6.57,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "EUR",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#VOD": freezeSpec({
      symbol: "#VOD",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -6.99,
      swapShort: -7.99,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "GBP",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    "#VOW": freezeSpec({
      symbol: "#VOW",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.01,
      leverage: 1,
      commission: 0.1,
      swapLong: -5.57,
      swapShort: -6.57,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "EUR",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    DE30: freezeSpec({
      symbol: "DE30",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.25,
      leverage: 25,
      commission: 1,
      swapLong: -137.42,
      swapShort: -331.03,
      swap3DayWeekday: 5,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    EURGBP: freezeSpec({
      symbol: "EURGBP",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1.32,
      leverage: 100000,
      commission: 1,
      swapLong: -4.23,
      swapShort: 0.33,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "GBP",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    EURJPY: freezeSpec({
      symbol: "EURJPY",
      broker: "finex",
      pip: 0.001,
      tickSize: 0.001,
      tickValue: 0.63,
      leverage: 100000,
      commission: 1,
      swapLong: 0.91,
      swapShort: -5.96,
      swapWedMultiplier: 3,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "JPY",
      isJPYPair: true,
      status: "VERIFIED",
    }),
    EURNZD: freezeSpec({
      symbol: "EURNZD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.56,
      leverage: 100000,
      commission: 1,
      swapLong: -1.9,
      swapShort: -2.37,
      swap3DayWeekday: 3,
      baseCurrency: "EUR",
      quoteCurrency: "NZD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    GBPAUD: freezeSpec({
      symbol: "GBPAUD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.7,
      leverage: 100000,
      commission: 1,
      swapLong: -1.11,
      swapShort: -3.31,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "AUD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    GBPCAD: freezeSpec({
      symbol: "GBPCAD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.7,
      leverage: 100000,
      commission: 1,
      swapLong: -2.24,
      swapShort: -5.21,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "CAD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    GBPCHF: freezeSpec({
      symbol: "GBPCHF",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1.2,
      leverage: 100000,
      commission: 1,
      swapLong: 0.05,
      swapShort: -6.29,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "CHF",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    GBPJPY: freezeSpec({
      symbol: "GBPJPY",
      broker: "finex",
      pip: 0.001,
      tickSize: 0.001,
      tickValue: 0.63,
      leverage: 100000,
      commission: 1,
      swapLong: 0.95,
      swapShort: -21.14,
      swapWedMultiplier: 3,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "JPY",
      isJPYPair: true,
      status: "VERIFIED",
    }),
    GBPNZD: freezeSpec({
      symbol: "GBPNZD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.56,
      leverage: 100000,
      commission: 1,
      swapLong: -4.45,
      swapShort: -5.43,
      swap3DayWeekday: 3,
      baseCurrency: "GBP",
      quoteCurrency: "NZD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    GBXUSD: freezeSpec({
      symbol: "GBXUSD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1,
      leverage: 100000,
      commission: 1,
      swapLong: -0.8,
      swapShort: -0.1,
      swap3DayWeekday: 3,
      baseCurrency: "GBX",
      quoteCurrency: "GBX",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    HK50: freezeSpec({
      symbol: "HK50",
      broker: "finex",
      pip: 1,
      tickSize: 1,
      tickValue: 5,
      leverage: 5,
      commission: 1,
      swapLong: -158.51,
      swapShort: -351.15,
      swap3DayWeekday: 5,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    JP225: freezeSpec({
      symbol: "JP225",
      broker: "finex",
      pip: 1,
      tickSize: 1,
      tickValue: 5,
      leverage: 5,
      commission: 1,
      swapLong: -6.95,
      swapShort: -6.18,
      swap3DayWeekday: 5,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    NZDCAD: freezeSpec({
      symbol: "NZDCAD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.7,
      leverage: 100000,
      commission: 1,
      swapLong: -0.44,
      swapShort: -1.96,
      swap3DayWeekday: 3,
      baseCurrency: "NZD",
      quoteCurrency: "CAD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    NZDCHF: freezeSpec({
      symbol: "NZDCHF",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1.2,
      leverage: 100000,
      commission: 1,
      swapLong: 0.71,
      swapShort: -4.21,
      swap3DayWeekday: 3,
      baseCurrency: "NZD",
      quoteCurrency: "CHF",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    NZDUSD: freezeSpec({
      symbol: "NZDUSD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1,
      leverage: 100000,
      commission: 1,
      swapLong: -1.36,
      swapShort: -0.51,
      swap3DayWeekday: 3,
      baseCurrency: "NZD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    UK100: freezeSpec({
      symbol: "UK100",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.1,
      leverage: 10,
      commission: 1,
      swapLong: -43.26,
      swapShort: -407.58,
      swap3DayWeekday: 5,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    US30: freezeSpec({
      symbol: "US30",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.05,
      leverage: 5,
      commission: 1,
      swapLong: -23.17,
      swapShort: -534.13,
      swap3DayWeekday: 5,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    US500: freezeSpec({
      symbol: "US500",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 0.5,
      leverage: 50,
      commission: 1,
      swapLong: -2.47,
      swapShort: -95.59,
      swap3DayWeekday: 5,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    USDCAD: freezeSpec({
      symbol: "USDCAD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.7,
      leverage: 100000,
      commission: 1,
      swapLong: -2.97,
      swapShort: -1.12,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "CAD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    USDEUR: freezeSpec({
      symbol: "USDEUR",
      broker: "finex",
      pip: 0.00000001,
      tickSize: 0.00000001,
      tickValue: 0,
      leverage: 1000,
      commission: 1,
      swapLong: -0.8,
      swapShort: -0.1,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "EUR",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    USDGBP: freezeSpec({
      symbol: "USDGBP",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 1.32,
      leverage: 100000,
      commission: 1,
      swapLong: 0,
      swapShort: 0,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "GBP",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    USDHKD: freezeSpec({
      symbol: "USDHKD",
      broker: "finex",
      pip: 0.00001,
      tickSize: 0.00001,
      tickValue: 0.13,
      leverage: 100000,
      commission: 1,
      swapLong: -1.11,
      swapShort: -6.01,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "HKD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    XAGUSD: freezeSpec({
      symbol: "XAGUSD",
      broker: "finex",
      pip: 0.001,
      tickSize: 0.001,
      tickValue: 0.1,
      leverage: 5000,
      commission: 1,
      swapLong: -9.96,
      swapShort: 0.01,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    XAUUSD: freezeSpec({
      symbol: "XAUUSD",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 10,
      leverage: 100,
      commission: 1,
      swapLong: -45.9,
      swapShort: 0.98,
      swap3DayWeekday: 3,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),
    XTIUSD: freezeSpec({
      symbol: "XTIUSD",
      broker: "finex",
      pip: 0.01,
      tickSize: 0.01,
      tickValue: 10,
      leverage: 1000,
      commission: 1,
      swapLong: -6.68,
      swapShort: -8.53,
      swap3DayWeekday: 5,
      baseCurrency: "USD",
      quoteCurrency: "USD",
      isJPYPair: false,
      status: "VERIFIED",
    }),

  });

export const OTB_SPECS_32: readonly string[] = Object.freeze([
  "AUDCAD_ORB",
  "AUDCHF_ORB",
  "AUDJPY_ORB",
  "AUDNZD_ORB",
  "AUDUSD_ORB",
  "CADJPY_ORB",
  "CHFJPY_ORB",
  "EURAUD_ORB",
  "EURCAD_ORB",
  "EURCHF_ORB",
  "GBPAUD_ORB",
  "GBPUSD_ORB",
  "NZDJPY_ORB",
  "USDCAD_ORB",
  "USDCHF_ORB",
  "USDJPY_ORB",
  "XAGUSD_ORB",
  "XAUUSD_ORB",
  "EURGBP_ORB",
  "EURJPY_ORB",
  "EURNZD_ORB",
  "EURUSD_ORB",
  "GBPCAD_ORB",
  "GBPJPY_ORB",
  "GBPNZD_ORB",
  "NZDUSD_ORB",
  "US100.DEC",
  "US30.DEC",
  "US500.DEC",
  "CLU",
  "AAPL.US",
  "AIG.US",
  "AMAZON.US",
  "AMZN.US",
  "APPLE.US",
  "AXP.US",
  "BA.US",
  "BABA.US",
  "BAC.US",
  "BOA.US",
  "CITI.US",
  "CSCO.US",
  "CVX.US",
  "DISNEY.US",
  "EBAY.US",
  "FB.US",
  "GE.US",
  "GOOG.US",
  "GS.US",
  "HPQ.US",
  "IBM.US",
  "INTC.US",
  "JNJ.US",
  "JPM.US",
  "KO.US",
  "MA.US",
  "MCD.US",
  "META.US",
  "MSFT.US",
  "NVDA.US",
  "ORCL.US",
  "PFE.US",
  "PG.US",
  "SBUX.US",
  "T.US",
  "V.US",
  "WMT.US",
  "XOM.US",
]);

export const FINEX_SPECS_32: readonly string[] = Object.freeze([
  "AUDCAD",
  "AUDCHF",
  "AUDJPY",
  "AUDNZD",
  "AUDUSD",
  "CADJPY",
  "CHFJPY",
  "EURAUD",
  "EURCAD",
  "EURCHF",
  "EURUSD",
  "GBPUSD",
  "NZDJPY",
  "USDCHF",
  "USDJPY",
  "US100",
  "#168",
  "#388",
  "#700",
  "#763",
  "#AA",
  "#AAPL",
  "#ADBE",
  "#ADS",
  "#AIG",
  "#ALV",
  "#AMGN",
  "#AXP",
  "#BA",
  "#BIDU",
  "#BLK",
  "#BMW",
  "#BP",
  "#CAT",
  "#CME",
  "#GE",
  "#GOOGL",
  "#GS",
  "#GSK",
  "#HD",
  "#HSBA",
  "#IBM",
  "#JNJ",
  "#JPM",
  "#MA",
  "#MAR",
  "#MCD",
  "#META",
  "#MMM",
  "#MSFT",
  "#NKE",
  "#NVDA",
  "#ORCL",
  "#RL",
  "#SAP",
  "#VOD",
  "#VOW",
  "DE30",
  "EURGBP",
  "EURJPY",
  "EURNZD",
  "GBPAUD",
  "GBPCAD",
  "GBPCHF",
  "GBPJPY",
  "GBPNZD",
  "GBXUSD",
  "HK50",
  "JP225",
  "NZDCAD",
  "NZDCHF",
  "NZDUSD",
  "UK100",
  "US30",
  "US500",
  "USDCAD",
  "USDEUR",
  "USDGBP",
  "USDHKD",
  "XAGUSD",
  "XAUUSD",
  "XTIUSD",
]);

/** Lookup exact (case-sensitive); null bila simbol tidak terdaftar. */
export function getInstrumentSpec32(symbol: string): InstrumentSpec | null {
  return INSTRUMENT_SPECS_32[symbol] ?? null;
}

/** True bila simbol terdaftar dengan status VERIFIED. */
export function isSpec32Verified(symbol: string): boolean {
  return getInstrumentSpec32(symbol)?.status === "VERIFIED";
}

/** Daftar simbol JPY (quote JPY) dari 32 specs. */
export function getJPYPairSymbols32(): string[] {
  return Object.values(INSTRUMENT_SPECS_32)
    .filter((spec) => spec.isJPYPair)
    .map((spec) => spec.symbol);
}
