/**
 * Tahap 4A — preset instrumen OrbiTraderBerjangka (isolated, DATA ONLY).
 *
 * - Satu-satunya sumber data spesifikasi OTB terverifikasi.
 * - BELUM di-wire ke applyBrokerPreset/validator/registry
 *   (wiring = Tahap 4B). Modul ini tidak mengubah perilaku runtime apa pun.
 * - Hanya simbol dengan data Specification terverifikasi yang terdaftar;
 *   simbol lain mengembalikan null (tanpa angka fiktif, tanpa salinan Finex).
 * - Simbol OTB dicocokkan EXACT (suffiks seperti _ORB signifikan);
 *   JANGAN dinormalisasi via normalizeSymbol (itu akan memangkas
 *   "GBPUSD_ORB" menjadi "GBPUSD" milik Finex).
 * - Bid/Ask transient (data pasar) SENGAJA tidak disimpan di preset.
 */

export type OtbSpreadMode = "floating" | "fixed";

export type OtbCalculationMode = "Forex" | "CFD" | "Futures";

export type OtbSwapType = "flat" | "percentage";

export interface OtbCommission {
  readonly volumeMin: number;
  readonly volumeMax: number;
  readonly pricePerLot: number;
}

export interface OtbInstrumentProfile {
  readonly symbol: string;
  readonly digits: number;
  readonly contractSize: number;
  readonly spreadMode: OtbSpreadMode;
  /** Stops level sesuai satuan Specification (points). */
  readonly stopsLevel: number;
  /** Minimum OTB. Jangan paksa di bawah nilai ini saat wiring. */
  readonly minVolume: number;
  readonly maxVolume: number;
  readonly volumeStep: number;
  /** Diinferensi dari digits=5 (standar Forex); verifikasi ulang bila ragu. */
  readonly tickSize: number;
  /** null = TBD; hitung via calculateOtbTickValue (bukan hardcoded). */
  readonly tickValue: number | null;  /** TERPISAH dari tick calculation. */
  readonly initialMargin: number;
  readonly maintenanceMargin: number;
  readonly hedgedMargin: number;
  readonly currencyProfit: string;
  readonly currencyMargin: string;
  /** Base currency simbol (terverifikasi dari Specification). */
  readonly contractCurrency: string;
  readonly calculationMode: OtbCalculationMode;
  readonly commission: OtbCommission | null;
  /** Tahap 5D-EXT1: jenis kalkulasi swap. "flat" = unit
   * profit-currency/lot/hari (3 verified); "percentage" = % per hari
   * dari nosional (contractSize × currentPrice), unit contract-base
   * currency (10 simbol baru). Fallback "flat" bila null/undefined. */
  readonly swapType: OtbSwapType | null;
  /** Nilai spec. Flat: unit profit-currency per lot per hari (per MT5
   * Specification, dikonfirmasi Tahap 5C-Step-2). Percentage: % per hari
   * (negatif = biaya, jangan dikali -1 lagi). Konversi FX menyusul
   * Tahap 5E. */
  readonly swapLong: number | null;
  /** Sama dengan swapLong (unit + sumber sama). */
  readonly swapShort: number | null;
}

function freezeOtbProfile(
  profile: OtbInstrumentProfile
): OtbInstrumentProfile {
  if (profile.commission !== null) {
    Object.freeze(profile.commission);
  }
  return Object.freeze(profile);
}

/**
 * Preset OTB terverifikasi dari Specification (per 02 Okt 2026),
 * cross-check ekspor CSV terminal OTB 03 Okt 2026 (Tahap 6E).
 *
 * Catatan data:
 * - tickValue tersimpan dalam PROFIT currency (nilainya sama dengan
 *   calculateOtbTickValue; cross-check di test). Konversi ke USD untuk
 *   pair non-USD-quote (AUDCAD, EURCHF) butuh rate — TBD tahap lanjut.
 *   (Kolom Tick_Value CSV memakai konvensi deposit-USD, mis. AUDCAD 0.70;
 *   bukan konflik, hanya konvensi berbeda.)
 * - Field AUDCAD_ORB/EURCHF_ORB terkonfirmasi CSV Tahap 6E (kolom baru
 *   03 Okt 2026): Stops_Level=20, Volume_Step=0.10, MaxVolume=10,
 *   margin 100000/100000/50000, Forex, profit=quote, margin=USD,
 *   komisi 33.00. spreadMode floating = default kelas (tidak ada di
 *   ekspor CSV, sama seperti 11 simbol lain).
 * - Komisi 33/lot dipertahankan (keputusan 6E); kolom Commission=0.00
 *   pada CSV dianggap tidak berlaku untuk akun ini.
 */
export const OTB_PRESETS: Record<string, OtbInstrumentProfile> =
  Object.freeze({
    GBPUSD_ORB: freezeOtbProfile({
      symbol: "GBPUSD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "GBP",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -2.25,
      swapShort: -0.75,
    }),
    AUDCAD_ORB: freezeOtbProfile({
      symbol: "AUDCAD_ORB",
      digits: 5,
      contractSize: 100000,
      // CSV 6E: floating (default kelas; tidak ada di ekspor).
      spreadMode: "floating",
      // CSV 6E: Stops_Level=20 terkonfirmasi.
      stopsLevel: 20,
      minVolume: 0.1,
      // CSV 6E: maxVolume=10 terkonfirmasi.
      maxVolume: 10,
      // CSV 6E: Volume_Step=0.10 terkonfirmasi.
      volumeStep: 0.1,
      tickSize: 0.00001,
      // Nilai spec (unit profit currency, CAD); sama dengan kalkulator.
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "CAD",
      currencyMargin: "USD",
      contractCurrency: "AUD",
      calculationMode: "Forex",
      // CSV 6E: Commission 33.00 (0.01-1000 lot) terkonfirmasi.
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -0.75,
      swapShort: -2.25,
    }),
    EURCHF_ORB: freezeOtbProfile({
      symbol: "EURCHF_ORB",
      digits: 5,
      contractSize: 100000,
      // CSV 6E: floating (default kelas; tidak ada di ekspor).
      spreadMode: "floating",
      // CSV 6E: Stops_Level=20 terkonfirmasi.
      stopsLevel: 20,
      minVolume: 0.1,
      // CSV 6E: maxVolume=10 terkonfirmasi.
      maxVolume: 10,
      // CSV 6E: Volume_Step=0.10 terkonfirmasi.
      volumeStep: 0.1,
      tickSize: 0.00001,
      // Nilai spec (unit profit currency, CHF); sama dengan kalkulator.
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "CHF",
      currencyMargin: "USD",
      contractCurrency: "EUR",
      calculationMode: "Forex",
      // CSV 6E: Commission 33.00 (0.01-1000 lot) terkonfirmasi.
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -1.75,
      swapShort: -1.25,
    }),
    AUDCHF_ORB: freezeOtbProfile({
      symbol: "AUDCHF_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "CHF",
      currencyMargin: "USD",
      contractCurrency: "AUD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    AUDJPY_ORB: freezeOtbProfile({
      symbol: "AUDJPY_ORB",
      digits: 3,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 100,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "JPY",
      currencyMargin: "USD",
      contractCurrency: "AUD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.25,
      swapShort: -1.75,
    }),
    AUDNZD_ORB: freezeOtbProfile({
      symbol: "AUDNZD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "NZD",
      currencyMargin: "USD",
      contractCurrency: "AUD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.25,
      swapShort: -1.75,
    }),
    AUDUSD_ORB: freezeOtbProfile({
      symbol: "AUDUSD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "AUD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    CADJPY_ORB: freezeOtbProfile({
      symbol: "CADJPY_ORB",
      digits: 3,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 100,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "JPY",
      currencyMargin: "USD",
      contractCurrency: "CAD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.25,
      swapShort: -1.75,
    }),
    CHFJPY_ORB: freezeOtbProfile({
      symbol: "CHFJPY_ORB",
      digits: 3,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 100,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "JPY",
      currencyMargin: "USD",
      contractCurrency: "CHF",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.75,
      swapShort: -1.25,
    }),
    EURAUD_ORB: freezeOtbProfile({
      symbol: "EURAUD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "AUD",
      currencyMargin: "USD",
      contractCurrency: "EUR",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    EURCAD_ORB: freezeOtbProfile({
      symbol: "EURCAD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "CAD",
      currencyMargin: "USD",
      contractCurrency: "EUR",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.25,
      swapShort: -1.75,
    }),
    GBPAUD_ORB: freezeOtbProfile({
      symbol: "GBPAUD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "AUD",
      currencyMargin: "USD",
      contractCurrency: "GBP",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -0.75,
      swapShort: -2.25,
    }),
    USDCAD_ORB: freezeOtbProfile({
      symbol: "USDCAD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "CAD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    // Tahap 6H: 3 simbol baru dari ekspor CSV terminal OTB 03 Okt 2026
    // (kolom 26: Stops=20, Step=0.10, margin 100000/100000/50000, Forex,
    // Profit=quote, Margin=USD, Commission 33.00). tickValue konvensi
    // profit-currency (JPY: 0.001×100000=100).
    NZDJPY_ORB: freezeOtbProfile({
      symbol: "NZDJPY_ORB",
      digits: 3,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 100,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "JPY",
      currencyMargin: "USD",
      contractCurrency: "NZD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    USDCHF_ORB: freezeOtbProfile({
      symbol: "USDCHF_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "CHF",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    USDJPY_ORB: freezeOtbProfile({
      symbol: "USDJPY_ORB",
      digits: 3,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 100,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "JPY",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.0,
      swapShort: -2.0,
    }),
    // ===== Tahap 6I (06 Okt 2026): 52 simbol dari bulk export
    // SymbolSpecs_OTB_1791247136.csv. Aturan mapping (terdokumentasi):
    // - tickSize/contractSize/stops/volumes/margins = verbatim CSV;
    // - tickValue = tickSize*contractSize (5d forex=1, JPY=100,
    //   preseden 16 simbol; cocok Tick_Value CSV bila konsisten);
    // - currencyProfit = Profit_Currency CSV; margin = Margin_Currency;
    // - swapLong/Short verbatim; swapType: forex+metal percentage
    //   (preseden 13/16), indeks/oil flat (nilai 0), saham flat
    //   (bunga USD/lot/hari, plausibel .2/hari untuk 100 lembar).
    EURGBP_ORB: freezeOtbProfile({
      symbol: "EURGBP_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "GBP",
      currencyMargin: "USD",
      contractCurrency: "EUR",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.75,
      swapShort: -1.25,
    }),
    EURJPY_ORB: freezeOtbProfile({
      symbol: "EURJPY_ORB",
      digits: 3,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 100,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "JPY",
      currencyMargin: "USD",
      contractCurrency: "EUR",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.75,
      swapShort: -1.25,
    }),
    EURNZD_ORB: freezeOtbProfile({
      symbol: "EURNZD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "NZD",
      currencyMargin: "USD",
      contractCurrency: "EUR",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    EURUSD_ORB: freezeOtbProfile({
      symbol: "EURUSD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "EUR",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -2,
      swapShort: -1,
    }),
    GBPCAD_ORB: freezeOtbProfile({
      symbol: "GBPCAD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "CAD",
      currencyMargin: "USD",
      contractCurrency: "GBP",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.75,
      swapShort: -1.25,
    }),
    GBPJPY_ORB: freezeOtbProfile({
      symbol: "GBPJPY_ORB",
      digits: 3,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 100,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "JPY",
      currencyMargin: "USD",
      contractCurrency: "GBP",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.75,
      swapShort: -1.25,
    }),
    GBPNZD_ORB: freezeOtbProfile({
      symbol: "GBPNZD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "NZD",
      currencyMargin: "USD",
      contractCurrency: "GBP",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.25,
      swapShort: -1.75,
    }),
    NZDUSD_ORB: freezeOtbProfile({
      symbol: "NZDUSD_ORB",
      digits: 5,
      contractSize: 100000,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.00001,
      tickValue: 1,
      initialMargin: 100000,
      maintenanceMargin: 100000,
      hedgedMargin: 50000,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "NZD",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.75,
      swapShort: -1.25,
    }),
    XAGUSD_ORB: freezeOtbProfile({
      symbol: "XAGUSD_ORB",
      digits: 3,
      contractSize: 5000,
      spreadMode: "floating",
      stopsLevel: 30,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.001,
      tickValue: 5,
      initialMargin: 400000,
      maintenanceMargin: 400000,
      hedgedMargin: 200000,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "XAG",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -1.5,
      swapShort: -1.5,
    }),
    XAUUSD_ORB: freezeOtbProfile({
      symbol: "XAUUSD_ORB",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 200000,
      maintenanceMargin: 200000,
      hedgedMargin: 100000,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "XAU",
      calculationMode: "Forex",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "percentage",
      swapLong: -2,
      swapShort: -1,
    }),
    CLU: freezeOtbProfile({
      symbol: "CLU",
      digits: 2,
      contractSize: 1000,
      spreadMode: "floating",
      stopsLevel: 1,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 10,
      initialMargin: 1000,
      maintenanceMargin: 1000,
      hedgedMargin: 500,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "CFD",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: 0,
      swapShort: 0,
    }),
    "US100.DEC": freezeOtbProfile({
      symbol: "US100.DEC",
      digits: 2,
      contractSize: 20,
      spreadMode: "floating",
      stopsLevel: 100,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.25,
      tickValue: 5,
      initialMargin: 2500,
      maintenanceMargin: 2500,
      hedgedMargin: 1250,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "CFD",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: 0,
      swapShort: 0,
    }),
    "US30.DEC": freezeOtbProfile({
      symbol: "US30.DEC",
      digits: 0,
      contractSize: 5,
      spreadMode: "floating",
      stopsLevel: 10,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 1,
      tickValue: 5,
      initialMargin: 2500,
      maintenanceMargin: 2500,
      hedgedMargin: 1250,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "CFD",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: 0,
      swapShort: 0,
    }),
    "US500.DEC": freezeOtbProfile({
      symbol: "US500.DEC",
      digits: 2,
      contractSize: 50,
      spreadMode: "floating",
      stopsLevel: 100,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.25,
      tickValue: 12.5,
      initialMargin: 2500,
      maintenanceMargin: 2500,
      hedgedMargin: 1250,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "CFD",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: 0,
      swapShort: 0,
    }),
    "AAPL.US": freezeOtbProfile({
      symbol: "AAPL.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "AIG.US": freezeOtbProfile({
      symbol: "AIG.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "AMAZON.US": freezeOtbProfile({
      symbol: "AMAZON.US",
      digits: 2,
      contractSize: 1,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 0.01,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -10,
      swapShort: -10,
    }),
    "AMZN.US": freezeOtbProfile({
      symbol: "AMZN.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "APPLE.US": freezeOtbProfile({
      symbol: "APPLE.US",
      digits: 2,
      contractSize: 1,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 0.01,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -10,
      swapShort: -10,
    }),
    "AXP.US": freezeOtbProfile({
      symbol: "AXP.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "BA.US": freezeOtbProfile({
      symbol: "BA.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "BABA.US": freezeOtbProfile({
      symbol: "BABA.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "BAC.US": freezeOtbProfile({
      symbol: "BAC.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "BOA.US": freezeOtbProfile({
      symbol: "BOA.US",
      digits: 2,
      contractSize: 1,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 0.01,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -10,
      swapShort: -10,
    }),
    "CITI.US": freezeOtbProfile({
      symbol: "CITI.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "CSCO.US": freezeOtbProfile({
      symbol: "CSCO.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 5,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "CVX.US": freezeOtbProfile({
      symbol: "CVX.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "DISNEY.US": freezeOtbProfile({
      symbol: "DISNEY.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "EBAY.US": freezeOtbProfile({
      symbol: "EBAY.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "FB.US": freezeOtbProfile({
      symbol: "FB.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "GE.US": freezeOtbProfile({
      symbol: "GE.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "GOOG.US": freezeOtbProfile({
      symbol: "GOOG.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "GS.US": freezeOtbProfile({
      symbol: "GS.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "HPQ.US": freezeOtbProfile({
      symbol: "HPQ.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "IBM.US": freezeOtbProfile({
      symbol: "IBM.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "INTC.US": freezeOtbProfile({
      symbol: "INTC.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "JNJ.US": freezeOtbProfile({
      symbol: "JNJ.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "JPM.US": freezeOtbProfile({
      symbol: "JPM.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "KO.US": freezeOtbProfile({
      symbol: "KO.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "MA.US": freezeOtbProfile({
      symbol: "MA.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "MCD.US": freezeOtbProfile({
      symbol: "MCD.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 10,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "META.US": freezeOtbProfile({
      symbol: "META.US",
      digits: 2,
      contractSize: 1,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 0.01,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -10,
      swapShort: -10,
    }),
    "MSFT.US": freezeOtbProfile({
      symbol: "MSFT.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "NVDA.US": freezeOtbProfile({
      symbol: "NVDA.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "ORCL.US": freezeOtbProfile({
      symbol: "ORCL.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "PFE.US": freezeOtbProfile({
      symbol: "PFE.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "PG.US": freezeOtbProfile({
      symbol: "PG.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "SBUX.US": freezeOtbProfile({
      symbol: "SBUX.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "T.US": freezeOtbProfile({
      symbol: "T.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "V.US": freezeOtbProfile({
      symbol: "V.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "WMT.US": freezeOtbProfile({
      symbol: "WMT.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
    "XOM.US": freezeOtbProfile({
      symbol: "XOM.US",
      digits: 2,
      contractSize: 100,
      spreadMode: "floating",
      stopsLevel: 20,
      minVolume: 0.1,
      maxVolume: 20,
      volumeStep: 0.1,
      tickSize: 0.01,
      tickValue: 1,
      initialMargin: 0,
      maintenanceMargin: 0,
      hedgedMargin: 1,
      currencyProfit: "USD",
      currencyMargin: "USD",
      contractCurrency: "USD",
      calculationMode: "Futures",
      commission: {
        volumeMin: 0.01,
        volumeMax: 1000,
        pricePerLot: 33,
      },
      swapType: "flat",
      swapLong: -3.2,
      swapShort: -2.8,
    }),
  });

/**
 * Mengambil preset OTB terverifikasi, atau null bila simbol belum
 * terverifikasi (termasuk nama simbol Finex — tanpa kontaminasi silang).
 */
export function getOtbInstrumentProfile(
  symbol: string
): OtbInstrumentProfile | null {
  return OTB_PRESETS[symbol] ?? null;
}

/**
 * Tick value turunan untuk mode Forex: tickSize * contractSize.
 * GBPUSD_ORB: 0.00001 * 100000 = 1.00 USD per tick per lot.
 * Murni (tidak membaca/menulis state); dipakai saat wiring Tahap 4B.
 */
export function calculateOtbTickValue(
  profile: OtbInstrumentProfile
): number {
  return profile.tickSize * profile.contractSize;
}

/** Kebutuhan margin OTB per simbol (data-layer, display-only). */
export interface OtbMarginRequirements {
  readonly symbol: string;
  readonly initialMargin: number;
  readonly maintenanceMargin: number;
  readonly hedgedMargin: number;
}

/**
 * Tahap 6G: ambil kebutuhan margin OTB, atau null bila simbol belum
 * terdaftar. Nilai dari ekspor CSV terminal (OTB statis:
 * 100000/100000/50000 untuk FX). Murni; TIDAK dipakai decision engine
 * (tanpa validasi margin otomatis) — display-only sampai ada kebutuhan.
 */
export function getOtbMarginRequirements(
  symbol: string
): OtbMarginRequirements | null {
  const preset = getOtbInstrumentProfile(symbol);

  if (preset === null) return null;

  return Object.freeze({
    symbol: preset.symbol,
    initialMargin: preset.initialMargin,
    maintenanceMargin: preset.maintenanceMargin,
    hedgedMargin: preset.hedgedMargin,
  });
}
